### PR TITLE
Enhancement to optionally format exported modules using black standard

### PR DESCRIPTION
**Pull request by butchland**
This will add a `black_compat` flag in the `settings.ini` file (default `False`).  If enabled, the exported python modules (including `_modidx.py`) are reformatted so they comply with the black standard. 

See [black for more info](https://black.readthedocs.io/en/stable/)

Dependencies added: 
    * [black](https://pypi.org/project/black/) (whether you're using it or not)

### CODE REVIEW

**Comment by hamelsmu** [comment]
Thanks for this PR.  I think this feature is a good idea (as many teams I work on use black), however, I am not sure we want to implement it this way.  I would rather use the processor machinery to reformat the code rather than do this separately while writing the files.  (It would probably result in dramatically less code, too if implemented via a processor)!

I can work on this and tag you in the PR so you can see what I do, @butchland if you are interested.

One thing we should discuss if we want to format the docs too with black if this option is turned on.  I wouldn't see the harm in that, so I would say format the code cells in docs too for consistency (I think people who use black like consistency).  

I'll close this PR for the time being, but I'll open an issue to track this.  cc @jph00

**Comment by jph00** [comment]
BTW when we implement this, we shouldn't make `black` a dependency - it should only be needed if the feature is used.

**Comment by hamelsmu** [comment]
Got it, like with an import inside a `try` block like you do in other places with similar situation

**Comment by butchland** [comment]
Hi @hamelsmu no problem at all.

I’ll be looking forward to seeing another approach as black is still just working  out an "official" public API. 

My approach was based on what another project called darker was using when it incorporated black. 

The other reason I used this approach was because I've been using nbdev along with nbqa which applies black and other linting tools to both notebook and python modules. 

The problem was that nbdev's exported modules did not comply with black. Running black on the exported modules would make me lose the ability to use nbdev_diff_nbs to check if my python code was in sync with the notebooks because black reformatted the exported modules. 

I have a branch in my nbdev fork that does that but I haven't made a PR for it because of a nasty bug I have been unable to resolve when I try running nbdev_test_nbs on my nbdev fork. But it's good enough for my own use so it's what I plan to use for my own projects.

Looking forward for nbdev2's  release real soon!

**Comment by hamelsmu** [comment]
This has been implemented via https://github.com/fastai/nbprocess/pull/61 in `04a_export.ipynb`

**Pull request closed without merging**
